extent.reporter.spark.start=true
extent.reporter.spark.out=Report/ExtentReport.html
extent.reporter.spark.config=src/main/resources/extent-config.xml

# Optional: add screenshots
screenshot.dir=Screenshots/screenshots/
screenshot.rel.path=../screenshots/

basefolder.name=Report/MyReport
basefolder.datetimepattern=dd-MMM-yy HH-mm-ss

systeminfo.user=QA Tester - Rajesh Mahor
systeminfo.environment=UAT
systeminfo.browser=Chrome
systeminfo.os=Windows 11